### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by talormanda** [PlexRipper/PlexRipper#179]
I left this running on my synology for a few days. My synology started throwing errors and the logs show plexripper crashed. Once this happened. My synology was normal again. I know this because of several log messages on my device:

`Docker container plexripper-plexripper stopped unexpectedly. Please select plexripper-plexripper on the Container page, click the Details button, and go to the Log tab for details.`

`Error | System | 12/06/2022 09:30:47 am | SYSTEM | [dotnet] stopped running because the system is out of memory.`

```
Event detected at
2022/10/17 12:01
 
Reason and effect
Some services such as SAN Manager or Snapshot Replication may be affected if the storage capacity runs out.
```

**Comment by JasonLandbridge** [comment]
Those are horrible to debug. :weary: PlexRipper writes its files to the Config/Logs directory, any chance you could get those?

**Comment by talormanda** [comment]
@JasonLandbridge - I mapped /Config/Logs and am waiting for it to crash again. It looks like it worked since a log of todays date was generated. So I guess I just need to wait for a crash again.

**Comment by JasonLandbridge** [comment]
Ah great! Thanks!

**Comment by talormanda** [comment]
@JasonLandbridge - Maybe this is related. I downloaded 1 movie that was around 8 GB. Hours later, the container is still holding onto almost 5 GB of memory. Why isn't this being released? I think this could be improved upon. It will just continue to eat more memory until it runs out and then weird things happen. Once I restarted the container, it went back to using 209 MB of memory idle.

**Comment by alafad** [comment]
I have the same issue, my Container fills up until he`s restarting by OOM Issues.

**Comment by JasonLandbridge** [comment]
I think I have fixed this issue now, the problem was indeed memory not being properly released when downloading and merging files.  

A new release ([0.10.0-RC-1](https://github.com/PlexRipper/PlexRipper/releases/tag/v0.10.0-RC1)) is available now on both the [latest](https://hub.docker.com/r/plexripper/plexripper/tags) and [dev](https://hub.docker.com/r/plexripper/plexripper/tags) docker channels, which contains all the changes/fixes from the past several months. Let me know if this fixes the issues.
