### ISSUE TITLE
Running PlexRipper on a Mac

### ISSUE THREAD

**Issue by keleko86** [PlexRipper/PlexRipper#186]
Hi all,

I'm quite new to this and would appreciate a bit of help.

I pulled the image from docker and now I am running it with "docker run plexripper/plexripper -p 7000:7000". These are the last lines from the log:
`06:35:32 [Information] [Boot.WaitForStartAsync] => Finished Initiating boot process
06:35:33 [Information] Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED started.
06:35:34 [Information] [Boot.OnStarted] => Boot.OnStarted has been called.`

However, going to localhost:7000 or localhost:7000/setup results in a blank page.

Any pointers on what I'm doing wrong? Thank you!

**Comment by JasonLandbridge** [comment]
A guide for Windows can be found here: https://github.com/PlexRipper/PlexRipper/issues/203
Which might be similar to Mac since Mac can also install Docker Desktop.

I will leave this issue open for now and try to figure out how to setup PlexRipper on Mac

If you have figured it out, it would be greatly appreciated if you can make a guide for others as well here:

https://www.plexripper.rocks/guides/installation/macos

**Comment by JasonLandbridge** [comment]
I finally got around to it, I created a guide with screenshots to install PlexRipper on a Mac machine: https://www.plexripper.rocks/guides/installation/macos

Closing this now in favor of that guide, feedback is very welcome!
