### ISSUE TITLE
Unraid - Connection refused 

### ISSUE THREAD

**Issue by Rielen** [PlexRipper/PlexRipper#195]
Just tried setting this up via Unraid OS - Able to login and pull servers however my server is unable to make a connection and DNS fix fails. Remote access shows successful within plex itself and the IP is correct within PlexRipper but still returns "Could not connect to server, it's most likely offline."

**Comment by JasonLandbridge** [comment]
I'm pretty sure that I have fixed this issue, in the new release multiple connections are checked instead of just the 1 previously. 

The new release ([0.10.0-RC-1](https://github.com/PlexRipper/PlexRipper/releases/tag/v0.10.0-RC1)) is available now on both the [latest](https://hub.docker.com/r/plexripper/plexripper/tags) and [dev](https://hub.docker.com/r/plexripper/plexripper/tags) docker channels, which contains all the changes/fixes from the past several months. Let me know if this fixes the issues.
