### ISSUE TITLE
[BUG] - There are no servers available

### ISSUE THREAD

**Issue by zach5444** [PlexRipper/PlexRipper#221]
### Checks

- [X] I have searched the existing issues for a similar bug and it does not exist!

### PlexRipper version

0.10.0 RC-1

### Platform

Windows

### Browsers

Google Chrome

### Description

My account is validated and enabled and selected, but I see There are no servers available. I am not sure why I am not seeing any remote server let alone mine.

I am running PlexRipper via Docker Desktop.

![2023-03-30 19_03_46-PlexRipper](https://user-images.githubusercontent.com/129471694/229005053-76051ccd-88af-4243-9199-d951c5dd3056.png)

### Reproduction steps

```bash
1. Launch PlexRipper on Docker Desktop
2. Access web gui
3. Add account, validate and save settings
4. Attempt to select server
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Logs

```bash
Removing logs because I'm unsure what data I might be exposing. Can provide additional info if needed. 
```

**Comment by JasonLandbridge** [comment]
Hi there, can you confirm that when you log into Plex.tv that you do have access to PlexServers?

**Comment by zach5444** [comment]
Thanks for the quick reply, but yeah I'm in right now watching Plex on another tab. No change on the PlexRipper page though.

**Comment by JasonLandbridge** [comment]
If you go through the logs you will see a `X-Plex-Token` code string, could you send this to plexripper@protonmail.com? That way I can test out what kind of data I'm getting back an be able to debug it. Thanks!

**Comment by zach5444** [comment]
Sure but I'm not certain where to pull the logs from. What I pasted when I opened the report was from the docker terminal.

I'm pretty new with docker and PlexRipper and still figuring things out. Can you tell me where I can find the logs?

**Comment by JasonLandbridge** [comment]
From the docker terminal is fine too, and the logs are in you 'Config' folder

**Comment by TryTryAgain** [comment]
Having the same issue, ssh'd into the running docker container and didn't find any relevant logs. Wouldn't sharing our  `X-Plex-Token` be handing over our admin user API key? Is there any other way we can help troubleshoot?

**Comment by JasonLandbridge** [comment]
> Having the same issue, ssh'd into the running docker container and didn't find any relevant logs. Wouldn't sharing our `X-Plex-Token` be handing over our admin user API key? 

Yes, but it can be easily invalidated [by signing out of the devices that use it](https://www.plexopedia.com/plex-media-server/general/plex-token/#regeneratetoken) and I'm honor bound not to abuse it or use it for myself in any way

> Is there any other way we can help troubleshoot?

Yeah in this case, some accounts work and some don't. Which is why I needed either credentials or a token of an account that didn't work, so I can debug. I was provided a token and another user created an account for me to use when testing so its on my to-do list. 

I'm currently doing a big migration/rewrite of the front-end, see [Nuxt v3](https://github.com/PlexRipper/PlexRipper/tree/NuxtV3) after which I can make a new release and solve the above problem.

**Comment by JasonLandbridge** [comment]
Closing this issue because this seems to have been fixed!
