### ISSUE TITLE
[BUG] - Browser freezes

### ISSUE THREAD

**Issue by alafad** [PlexRipper/PlexRipper#223]
### Checks

- [X] I have searched the existing issues for a similar bug and it does not exist!

### PlexRipper version

0.10.0-RC1

### Platform

Linux

### Browsers

Firefox, Chromium

### Description

If i enter a big library (about 300TB) my Firefox/Chromium freezes and with a bit luck and many team i can see the movie  titles but not their images. And if I Scroll down it hangs again...

Which browser/ settings can you recommend?

### Reproduction steps

```bash
goto http://ip:7000/movies/4
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Logs

```bash
WebSocket connection to 'ws://debian:7000/progress?id=BpSzeWz0bj6jAZIz6T0xAA' failed: 
(anonymous) @ 7c20396.js:2
7c20396.js:2 [2023-04-06T17:51:17.334Z] Information: (WebSockets transport) There was an error with the transport.
7c20396.js:2 [2023-04-06T17:51:17.346Z] Error: Failed to start the transport 'WebSockets': Error: WebSocket failed to connect. The connection could not be found on the server, either the endpoint may not be a SignalR endpoint, the connection ID is not present on the server, or there is a proxy blocking WebSockets. If you have multiple servers check that sticky sessions are enabled.
log @ 7c20396.js:2
7c20396.js:2 WebSocket connection to 'ws://debian:7000/notifications?id=O4v4HYEbKCK46WKSdP5jVg' failed: 
(anonymous) @ 7c20396.js:2
7c20396.js:2 [2023-04-06T17:58:19.013Z] Information: (WebSockets transport) There was an error with the transport.
7c20396.js:2 [2023-04-06T17:58:19.036Z] Error: Failed to start the transport 'WebSockets': Error: WebSocket failed to connect. The connection could not be found on the server, either the endpoint may not be a SignalR endpoint, the connection ID is not present on the server, or there is a proxy blocking WebSockets. If you have multiple servers check that sticky sessions are enabled.
log @ 7c20396.js:2
:7000/progress?id=1MtdRkrEbDy-VSnzaC7glA:1          Failed to load resource: the server responded with a status of 404 (Not Found)
7c20396.js:2 [2023-04-06T17:58:19.833Z] Error: Failed to start the transport 'ServerSentEvents': Error: EventSource failed to connect. The connection could not be found on the server, either the connection ID is not present on the server, or a proxy is refusing/buffering the connection. If you have multiple servers check that sticky sessions are enabled.
log @ 7c20396.js:2
7c20396.js:2 [2023-04-06T17:58:20.036Z] Information: SSE connected to http://debian:7000/notifications?id=JUPc6qntW_kNsTufWcNnOQ
7c20396.js:2 [2023-04-06T18:01:10.450Z] Information: Connection disconnected.
```

**Comment by JasonLandbridge** [comment]
Thanks for the bug report, yes I am aware of this problem and I am re-creating the entire user interface (front-end) so that should solve a big part of this. I'm hoping to have the new version out before the end of next week. 

I unfortunately don't have access to huge server, could you maybe provide me with your Plex token? 

If you go through the logs you will see an `X-Plex-Token` code string, could you send this to [plexripper@protonmail.com](mailto:plexripper@protonmail.com)? That way I can test out and ensure it's working, thanks!

**Comment by alafad** [comment]
You have got an email with plex credentials.

**Comment by DomMuc83** [comment]
Hey there :) anything „up to date“ to this ? 🤪🙈

**Comment by DomMuc83** [comment]
Anything?? Its a real cool project and works fine - but not for librarys with 15.000 or more items… 🙈

**Comment by JasonLandbridge** [comment]
Well all you had to say is that's it's a cool project and you will summon me :P

I'm fully aware of the problem and with the next update this will have been fixed. I will continue to work on this, this weekend at least, but I can't promise I will have it released then as well.

**Comment by alafad** [comment]
Does the shared account working for your testings? 

If you give me your plex username I can give you a 30 day access for this account.

**Comment by JasonLandbridge** [comment]
@alafad , yeah absolutely! Still many thanks for that, last 1.5 weeks have been busy with life but I can hopefully continue my work the coming weeks. It's a big update which I need to finish up before the next release, but I'm at least almost done!

You can keep an eye on the progress on this branch: [Branch NuxtV3](https://github.com/PlexRipper/PlexRipper/tree/NuxtV3 )
Also the upcoming changelog: [CHANGELOG.md](https://github.com/PlexRipper/PlexRipper/blob/NuxtV3/CHANGELOG.md)

**Comment by alafad** [comment]
No problem, take your time and don't stress yourself, the better the result will be..

**Comment by JasonLandbridge** [comment]
Jesus, this took way too long but I'm happy to report that this should now all be fixed! I've basically recreated the entire user interface, since it was quite outdated anyway, and I've paid special attention to huge libraries. I've tried huge libraries with 40000+ movies and it all works smoothly now.

The new [0.11 version](https://github.com/PlexRipper/PlexRipper/releases/tag/v0.11.0) has been released. Can you give it a try and let me know?

I'm closing this issue but please keep opening new issues if you have any problems!

Also huge shout-out to @alafad, thank you so much for the account!
