### ISSUE TITLE
[BUG] - If the IP address of a server changes, it will only update if the account is deleted and re-added

### ISSUE THREAD

**Issue by pcn** [PlexRipper/PlexRipper#284]
### Checks

- [X] I have searched the existing issues for a similar bug and it does not exist!

### PlexRipper version

v0.14.0-DEV1

### Platform

Linux

### Browsers

Firefox

### Description

A server changed addresses, and the old IP address was consistent. The server was not available until I deleted and re-added the account.

### Reproduction steps

```bash
1. Server changes address
2. Attempt to connect to server
3. Validating the server via "Server Connections" fails
4. No way to try to update the UI/settings with the new address
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Logs

```bash
I have no logs currently
```

**Comment by frosit** [comment]
I'm sorry but I don't really understand: "A server changed addresses, and the old IP address was consistent."

Because an IP is an address, and it doesn't seem consistent if it changes? Do you mean your public IP changed but your local IP remained the same? Which could be the case if you for example moved into a new home or something.

Despite my confusion, I don't think plexripper will check with plex if the endpoint (presumably the public IP of your plex server at the time of initial connection) has changed address. If this is what you mean, I think your right and we should mark this as a new feature perhaps?

**Comment by JasonLandbridge** [comment]
Pick server -> Server Settings -> Server Commands -> Inspecting a server should resolve this and get the latest connections to a server

![Screenshot_20240810_192132](https://github.com/user-attachments/assets/94cd9c3d-26bf-47eb-b5ea-50341fc13740)
