### ISSUE TITLE
💡 [REQUEST] - Alternative authentication methods, OAuth or PIN etc

### ISSUE THREAD

**Issue by mattheys** [PlexRipper/PlexRipper#313]
### Checks

- [X] I have searched the existing issue and my feature request does not exist!
- [X] I have tried out the latest development build and can confirm my feature request is not yet implemented!

### Describe the feature

I'm not keen on giving out my Plex credentials to 3rd party apps.  OAuth like Tautulli uses would be perfect for this.  

For now I've created a 2nd account and shared my media with my 2nd account so my main one can't get compromised but I think a lot of security conscious people would not be happy at entering their main username and password into a 3rd party app.

App looks great by the way, last year I went to write a nearly identical feature set app, I just didn't have the time and it fell by the wayside so I'm so glad this is basically exactly what I was going to write myself :-)

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Does this feature have a potential to break existing features?

**Comment by JasonLandbridge** [comment]
I completely understand your concern, you can be rest assured that any credentials entered are sent straight to plex.tv in the exact same way as you would normally enter your credentials when logging in. See: https://github.com/PlexRipper/PlexRipper/blob/9cbde2cbb961e21ba514f3c0f01810895966fc21/src/PlexApi/Api/PlexApi.cs#L46

The reason for this is that when you use the way Tautulli does it, plex.tv will "fingerprint" you and track where you're logging in from so to avoid that I opted to sent credentials directly while modifying the headers in a way where its supposed to be unique. PlexRipper is understandably a bit of a grey area which is why I want to minimize any tracking or identification as much as possible.

I can however add the possibility that you add an plex.tv authentication token directly, that would avoid the need for credentials.

**Comment by JasonLandbridge** [comment]
> I can however add the possibility that you add an plex.tv authentication token directly, that would avoid the need for credentials.

This has been added 
![Screenshot_20240810_183342](https://github.com/user-attachments/assets/3ff8dfab-adbb-4954-83f4-59819bb6c62f)
