### ISSUE TITLE
No libraries available

### ISSUE THREAD

**Issue by abra1c** [PlexRipper/PlexRipper#76]
![Screenshot 2021-09-27 201655](https://user-images.githubusercontent.com/56481925/134963743-6862e615-5067-4861-8475-c92c5934265e.png)
What am I doing wrong?

**Comment by abra1c** [comment]
Waited a few minutes and now it works.

**Comment by JasonLandbridge** [comment]
Yeah there is supposed to be a very nice interface showing the progress of the server being synced, but that got broken somehow so that is my highest priority to fix now. If all goes well I hope to have it fixed by tomorrow. There is currently a new version on PlexRipper Development with many fixes, I would recommend trying that image
